version: '2.3'
services:
  remote-runner:
    build: docker/remote-runner
    environment:
      - RELEASE_RUNNER_RELEASE_URL=http://localhost:5516
      - PROJECT_NAME=release-remote-runner
      - VERSION=24.1.6
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  container-registry:
    image: registry:2
    ports:
      - "5050:5000"
    volumes:
      - .:/var/lib/registry
