version: '2.3'
services:
  deploy:
    build: docker/xl-deploy
#    build: docker/xl-deploy-from-zip
    ports:
    - 4516:4516
    environment:
    - ADMIN_PASSWORD=admin

  release:
#    build: docker/xl-release
    build: docker/xl-release-from-zip
    ports:
    - 5516:5516
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y

  xl-cli:
    build: ./docker/xl-cli
    command: ["apply", "-v", "-f", "/data/configure-xl-devops-platform.yaml"]
    volumes:
    - ./docker/as-code:/data:ro

  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment: # warning this potentially opens up a security hole :)
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONTAINERS=1
      - EVENTS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - PLUGINS=1
      - POST=1
      - SECRETS=1
      - SERVICES=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VERSION=1
      - VOLUMES=1

  setup:
    build: ./scenario/setup
    depends_on:
      - deploy
      - release
    command: ["apply", "-v", "-f", "/data/setup.yaml"]
    volumes:
      - ./scenario/setup:/data:ro

  remote-runner:
    build: ./scenario/remote-runner
    depends_on:
      - setup
    environment:
      - RELEASE_RUNNER_RELEASE_URL=http://localhost:5516
      - PROJECT_NAME=release-remote-runner
      - VERSION=23.3.0
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  container-registry:
    image: registry:2
    ports:
      - "5050:5000"
    volumes:
      - .:/var/lib/registry
