version: '2.3'
services:
  deploy:
    build: docker/xl-deploy
#    build: docker/xl-deploy-from-zip
    ports:
    - 4516:4516
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
    networks:
      - demo-network

  release:
    build: docker/xl-release
#    build: docker/xl-release-from-zip
    ports:
    - 5516:5516
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
    - SERVER_URL=http://release:5516
    networks:
      - demo-network

  setup:
    build: demo-scenario
    depends_on:
      - deploy
      - release
    command: ["apply", "--verbose", "--detach", "--file", "/data/setup.yaml"]
    volumes:
      - ./demo-scenario:/data:ro
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
