services:
  deploy:
    build: docker/xl-deploy
#    build: docker/xl-deploy-from-zip
    ports:
    - 4516:4516
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
    networks:
      - demo-network

  release:
    build: docker/xl-release
#    build: docker/xl-release-from-zip
    ports:
    - 5516:5516
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
    - SERVER_URL=http://release:5516
    networks:
      - demo-network

  setup:
    build: demo-scenario
    depends_on:
      - deploy
      - release
    command: ["apply", "--detach", "--file", "/data/setup.yaml"]
    volumes:
      - ./demo-scenario:/data:ro
    networks:
      - demo-network

  remote-runner:
    build: docker/remote-runner
    environment:
      - RELEASE_RUNNER_RELEASE_URL=http://localhost:5516
      - PROJECT_NAME=release-remote-runner
      - VERSION=24.1.6
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  container-registry:
    image: registry:2
    ports:
      - "5050:5000"
    volumes:
      - .:/var/lib/registry

networks:
  demo-network:
    driver: bridge
