services:
  deploy:
    build: "${DEPLOY_DOCKER_PATH}"
    ports:
      - "4516:4516"
    environment:
      - ADMIN_PASSWORD=admin
      - ACCEPT_EULA=Y
    networks:
      - demo-network

  release:
    build: "${RELEASE_DOCKER_PATH}"
    ports:
      - "5516:5516"
    environment:
      - ADMIN_PASSWORD=admin
      - ACCEPT_EULA=Y
      - SERVER_URL=http://release:5516
    networks:
      - demo-network

  setup:
    build: demo-scenario
    depends_on:
      - deploy
      - release
    command: /data/run-commands.sh
    volumes:
      - ./demo-scenario:/data:ro
    networks:
      - demo-network

  remote-runner:
    build: docker/remote-runner
    depends_on:
      - setup
    environment:
      - RELEASE_RUNNER_RELEASE_URL=http://release:5516
      - RELEASE_RUNNER_DOCKER_DOCKER_HOST=remote-runner
      - RELEASE_RUNNER_DOCKER_RUN_ON_SAME_NETWORK=true
      - PROJECT_NAME=release-remote-runner
      - VERSION=24.1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    networks:
      - demo-network

  container-registry:
    image: registry:2
    ports:
      - "5050:5000"
    volumes:
      - .:/var/lib/registry
    networks:
      - demo-network

networks:
  demo-network:
    name: demo-network
    driver: bridge