# Offical
FROM xebialabsunsupported/xl-release:24.1

# Install license
COPY default-conf/xl-release-license.lic /opt/xebialabs/xl-release-server/default-conf/

# Install plugins
#RUN rm -f /opt/xebialabs/xl-release-server/default-plugins/xlr-official/xlr-relationships-plugin-*.jar
#COPY default-plugins /opt/xebialabs/xl-release-server/default-plugins
