apiVersion: xl-release/v1
kind: Templates
spec:
  - name: Local Deploy (Docker)
    type: digitalai.DeployServer
    url: !value deployUrl
    username: !value deployUsername
    password: !value deployPassword
