apiVersion: xl-release/v1
kind: Templates
spec:
  - type: xlrelease.ThemeSettings
    id: Configuration/settings/ThemeSettings
    headerName: Release & Deploy Together
    headerAccentColor: RED
    description: Instance for testing Release and Deploy together
---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Application Demo
spec:
- template: TestApp Deploy Pipeline
  phases:
  - phase: DEV
    tasks:
    - name: Ready for DEV?
      type: xlrelease.GateTask
      team: Release Admin
      precondition: "${confirmDeployment}"
    - name: Deploy to DEV
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/Hes/TestApp
      deploymentVersion: "${version}"
      deploymentPackage: "Applications/Users/Hes/TestApp/${version}"
      deploymentEnvironment: TestApp/DEV
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#3d6c9e'
  - phase: TEST
    tasks:
    - name: Ready for TEST?
      type: xlrelease.GateTask
      team: Release Admin
      precondition: "${confirmDeployment}"
    - name: Deploy to TEST
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/Hes/TestApp
      deploymentVersion: "1.0"
      deploymentPackage: Applications/Users/Hes/TestApp/1.0
      deploymentEnvironment: Environments/TestApp/TEST
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#498500'
  - phase: ACC
    tasks:
    - name: Ready for ACC?
      type: xlrelease.GateTask
      team: Release Admin
      precondition: "${confirmDeployment}"
    - name: Deploy to ACC
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/Hes/TestApp
      deploymentVersion: "1.0"
      deploymentPackage: Applications/Users/Hes/TestApp/1.0
      deploymentEnvironment: Environments/TestApp/ACC
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#ff9e49'
  - phase: PROD
    tasks:
    - name: Ready for PROD?
      type: xlrelease.GateTask
      team: Release Admin
      precondition: "${confirmDeployment}"
    - name: Deploy to PROD
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/Hes/TestApp
      deploymentVersion: "1.0"
      deploymentPackage: Applications/Users/Hes/TestApp/1.0
      deploymentEnvironment: Environments/TestApp/PROD
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#ff9e49'
  variables:
  - type: xlrelease.StringVariable
    key: version
    label: Version
    description: Version of the application to deploy. Auto-complete is supported
      in this field.
    value: "1.0"
  - type: xlrelease.BooleanVariable
    key: confirmDeployment
    label: Confirm deployments
  riskProfile: Default risk profile
  author: hes.siemelink@digital.ai
  defaultTargetFolder: ./
