apiVersion: xl-release/v1
kind: Templates
spec:
  - type: xlrelease.ThemeSettings
    id: Configuration/settings/ThemeSettings
    headerName: Live Deployments Demo
    headerAccentColor: GREEN
    description: Instance for testing Release and Deploy together
---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Application Demo
spec:
- template: Acme-Backend Deploy Pipeline
  phases:
  - phase: DEV
    tasks:
    - name: Deploy to DEV
      type: deploy.Deploy
      failureHandler: |-
        if (releaseVariables['attempt'] < 3):
          releaseVariables['attempt'] = releaseVariables['attempt'] + 1
          taskApi.retryTask(getCurrentTask().getId(), "Retrying task from failure handler.")
        else:
          taskApi.skipTask(getCurrentTask().getId(), "Skipped task from failure handler.")
      taskFailureHandlerEnabled: true
      taskRecoverOp: RUN_SCRIPT
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/me/Acme-Backend
      deploymentVersion: "${version}"
      deploymentPackage: "Applications/Users/me/Acme-Backend/${version}"
      deploymentEnvironment: Acme-Backend/DEV
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#3d6c9e'
  - phase: TEST
    tasks:
    - name: Deploy to TEST
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/me/Acme-Backend
      deploymentVersion: "${version}"
      deploymentPackage: "Applications/Users/me/Acme-Backend/${version}"
      deploymentEnvironment: Environments/Acme-Backend/TEST
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#498500'
  - phase: ACC
    tasks:
    - name: Deploy to ACC
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/me/Acme-Backend
      deploymentVersion: "${version}"
      deploymentPackage: "Applications/Users/me/Acme-Backend/${version}"
      deploymentEnvironment: Environments/Acme-Backend/ACC
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#ff9e49'
  - phase: PROD
    tasks:
    - name: Deploy to PROD
      type: deploy.Deploy
      server: Local Deploy (Docker)
      deploymentApplication: Applications/Users/me/Acme-Backend
      deploymentVersion: "${version}"
      deploymentPackage: "Applications/Users/me/Acme-Backend/${version}"
      deploymentEnvironment: Environments/Acme-Backend/PROD
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#ff9e49'
  variables:
  - type: xlrelease.StringVariable
    key: version
    label: Version
    description: Version of the application to deploy. Auto-complete is supported
      in this field.
    value: "1.0"
  - type: xlrelease.IntegerVariable
    key: attempt
    requiresValue: false
    showOnReleaseStart: false
  scriptUsername: admin
  scriptUserPassword: admin
- template: Cloud-native test procedure
  phases:
    - phase: Performance test
      tasks:
        - name: Wait for deployment in TEST
          type: webhook.WaitForDeploymentEvent
          deploymentStatuses:
            - success
        - name: Do performance testing
          type: xlrelease.Task
        - name: Performance approved
          type: xlrelease.GateTask
        - name: Promote application to ACC
          type: argocd.UpdateApplication
          capabilities:
            - remote
- template: Release to be used by trigger
  description: This is an demo template that will be started by trigger automatically
  scheduledStartDate: 2025-07-10T06:00:00Z
  phases:
    - phase: Checklist
      tasks:
        - name: Make sure release got started by trigger
          type: xlrelease.Task
        - name: is it working
          type: xlrelease.GateTask
          conditions:
            - name: Release was automatically created by trigger
              type: xlrelease.GateCondition
            - name: Release was automatically started by trigger
              type: xlrelease.GateCondition