apiVersion: xl-release/v1
kind: Templates
spec:
  - name: FluxCD Server Connection
    type: fluxcd.APIServer
    url: !value fluxUrl
    fluxcdAuthenticationMethod: Client Certificate
    insecure: true
    clientCrt: !value fluxCertificate
    clientKey: !value fluxKey
